### PR TITLE
removed tagline and centered logo (homepage)

### PR DESCRIPTION
**Pull request by sriramun**
minor CSS changes

### CODE REVIEW

**Comment by kernelpanic77** [comment]
@gr455 Please have a look, and check if it is fine. 
Thanks

**Review by gr455 — CHANGES_REQUESTED** [review]
Not mobile compatible. On big screen, vertical allignment looks slightly bottom skewed?

**Comment by gr455** [comment]
What does everyone think about this over the earlier design, :+1:  or :-1:

**Comment by vijay-jaisankar** [comment]
</img>

The firefox preview shows the logo being slightly off-center. 

Can anyone confirm this by trying to run it on your system, please?

## Steps to Reproduce:
- `gh checkout pr 19`
- `yarn start`
- Press F12 and click on the "mobile" icon

**Comment by vijay-jaisankar** [comment]
Also, @gr455 , I think we take the aforementioned vote to Slack, as many might not get not notified about this by virtue of not being involved with this issue.

**Comment by sriramun** [comment]
Please check if it's fine now?

**Comment by vijay-jaisankar** [comment]
Updated Zense Logo on Homepage

LGTM @sriramun :)
@gr455 Does this still hold in the current commit?
> Not mobile compatible. On big screen, vertical allignment looks slightly bottom skewed?

**Review by gr455 — APPROVED** [review]
Looks great now! little bottom skewed logo, but no worries, not a big deal

**Pull request merged**
