### PR TITLE
updated about page

### PR DESCRIPTION
**Pull request by sriramun**
added content from the old site and the student kit

>Who are we? We are a developers' community, run and managed entirely by students of IIIT-Bangalore, consisting of tech enthusiasts who seek to build and break things while working with the bleeding edge of technologies

> What do we do? Our goal is to unite passionate developers and provide them with a platform to collaborate and innovate. We organise seminars on new technologies, conduct hackathons and promote Open Source culture at IIIT Bangalore.

### CODE REVIEW

**Comment by vijay-jaisankar** [comment]
Hi @sriramun - nice work! 

> We are a developers' community, run and managed entirely by students of IIIT-Bangalore, consisting of tech enthusiasts who seek to build and break things while working with the bleeding edge of technologies

This line seems too long to read. Do you think we can change this?

**Comment by gr455** [comment]
> Hi @sriramun - nice work!
> 
> > We are a developers' community, run and managed entirely by students of IIIT-Bangalore, consisting of tech enthusiasts who seek to build and break things while working with the bleeding edge of technologies
> 
> This line seems too long to read. Do you think we can change this?

In my opinion it's fine becaue About is supposed to be kinda long. What do you think

**Comment by vijay-jaisankar** [comment]
>   We are a developers' community, run and managed entirely by students of IIIT-Bangalore, consisting of tech enthusiasts who seek to build and break things while working with the bleeding edge of technologies


The content here is fine, it can be split into two sentences imo @gr455

**Comment by sriramun** [comment]
> We are a group of tech enthusiasts from IIIT-Bangalore who seek to build and break things while working with the bleeding edge of technologies. Together, we form a skilled and zealous developers' community - Zense.

**Comment by vijay-jaisankar** [comment]
LGTM @sriramun 
Wdys @gr455

**Review by gr455 — APPROVED** [review]
@sriramun Can we make it so that the SVGs don't show up in mobile view. I'll merge this PR for now.

**Pull request merged**
